name: mozersubtitlebot
description: Dart telegram bot for converting  


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=2.6.0 <2.11.0"

dependencies:
  flutter:
    sdk: flutter

  teledart: ^0.0.50
  dio: ^3.0.10

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  flutter_driver:
#    sdk: flutter
#  test: any
#
#
#flutter:
#    uses-material-design: true

